### ISSUE TITLE
Failure to create compute instance

### ISSUE THREAD

**Issue by lenisha** [Azure-Samples/ai-studio-in-a-box#2]
Run azd up with default settings:

You can view detailed progress in the Azure Portal:
  (✓) Done: Resource group: rg-aiinabox
  (✓) Done: Virtual Network: vnet-aiinabox-bc7
  (✓) Done: Key Vault: kv-aiinabox-bc7
  (✓) Done: Storage account: staiinaboxbc7
  (✓) Done: Cognitive Service: cog-aiinabox-bc7
  (✓) Done: Private Endpoint: pl-staiinaboxbc7
  (✓) Done: Private Endpoint: pl-kv-aiinabox-bc7
  (✓) Done: Private Endpoint: pl-oai-cog-aiinabox-bc7
  (✓) Done: Private Endpoint: pl-cog-aiinabox-bc7
  (✓) Done: Search service: srch-aiinabox-bc7
  (✓) Done: Private Endpoint: pl-srch-aiinabox-bc7
  (✓) Done: Machine Learning Workspace: cog-hub-aiinabox-bc7
  (✓) Done: Machine Learning Workspace: cog-ai-prj-aiinabox-bc7
  |=====  | Creating/Updating resources
ERROR: error executing step command 'provision': deployment failed: error deploying infrastructure: deploying to subscription:

Deployment Error Details:
StorageMountError: The specified Azure ML Compute Instance vmaiinabox-bc7 setup failed with error "Failed to mount storage. Details - Hint:If you're using network security group rules, make sure to allow outbound connection to ports 443, 445 for storage service tag. For more details please visit aka.ms/AMLComputeVnet ". Please delete and try to recreate. If the problem persists, please follow up with Azure Support.
InvalidPrincipalId: A valid principal ID must be provided for role assignment.
InvalidPrincipalId: A valid principal ID must be provided for role assignment.
InvalidPrincipalId: A valid principal ID must be provided for role assignment.
InvalidPrincipalId: A valid principal ID must be provided for role assignment.

TraceID: 0d90cb236e263510e7095870c87ca3f4

**Comment by MarcoABCardoso** [comment]
Thank you for reporting @lenisha!

Compute instances are not currently supported for Hubs created with identity access from the start. This is being worked on by Azure AI team and will be fixed in the coming days. As a workaround, if you require computes and identity-based access, deploy your Hub with access keys first, and later switch to identity-based. This will trigger the required configurations.

Regarding the RBAC failures that follow - I've added instructions to create a new azd environment prior to running "azd up". This should properly run the preup hook which sets your principal ID.

Keeping this open until the compute issue is fixed.

**Comment by MarcoABCardoso** [comment]
Just a quick follow up - we've added a FAQ to target these issues.
Please let us know if any further assistance is required!

**Comment by IainD925** [comment]
> Just a quick follow up - we've added a FAQ to target these issues. Please let us know if any further assistance is required!

Hi Marco.  I tried deploying with identify-based access to no avail then deleted my local repo and re-created in a new directory, ensuring to create a new env, as shown in the following log.  First attempt failed so as per FAQ I retried, still failed.
Sensitive details removed.

`PS C:\> git clone https://github.com/Azure-Samples/ai-studio-in-a-box
Cloning into 'ai-studio-in-a-box'...
remote: Enumerating objects: 156, done.
remote: Counting objects: 100% (156/156), done.
remote: Compressing objects: 100% (122/122), done.
remote: Total 156 (delta 23), reused 153 (delta 20), pack-reused 0
Receiving objects: 100% (156/156), 15.54 MiB | 7.13 MiB/s, done.
Resolving deltas: 100% (23/23), done.
PS C:\> cd ai-studio-in-a-box
PS C:\ai-studio-in-a-box> azd auth login
Logged in to Azure.
PS C:\ai-studio-in-a-box> azd env new
? Enter a new environment name: [? for help] aibox

? Enter a new environment name: aibox
PS C:\ai-studio-in-a-box> azd up
? Select an Azure Subscription to use:  3. Microsoft Azure Sponsorship Subscription 3 (04xxxxxxxxxxxxxxxxxxxxxxxxxxxxx96b)
? Select an Azure location to use: 45. (US) East US 2 (eastus2)
? Enter a value for the 'deploySearch' infrastructure parameter: True
? Enter a value for the 'publicNetworkAccess' infrastructure parameter: Enabled
? Enter a value for the 'systemDatastoresAuthMode' infrastructure parameter: accessKey

Packaging services (azd package)


Provisioning Azure resources (azd provision)
Provisioning Azure resources can take some time.
                                                                                                                                                                                                                                                                                   Subscription: Microsoft Azure Sponsorship Subscription 3 (04xxxxxxxxxxxxxxxxxxxxxxxxxxxxx96b)
Location: East US 2

  You can view detailed progress in the Azure Portal:
  https://portal.azure.com/#view/HubsExtension/DeploymentDetailsBlade/~/overview/id/%2Fsubscriptions%2F04xxxxxxxxxxxxxxxxxxxxxxxxxxxxx96b%2Fproviders%2FMicrosoft.Resources%2Fdeployments%2Faibox-1722354903

  (✓) Done: Resource group: rg-aibox
  (✓) Done: Virtual Network: vnet-aibox-la5
  (✓) Done: Key Vault: kv-aibox-la5
  (✓) Done: Storage account: staiboxla5
  (✓) Done: Private Endpoint: pl-kv-aibox-la5
  (✓) Done: Private Endpoint: pl-staiboxla5
  (✓) Done: Search service: srch-aibox-la5
  (✓) Done: Private Endpoint: pl-srch-aibox-la5
  (✓) Done: Cognitive Service: cog-aibox-la5
  (x) Failed: Private Endpoint: pl-oai-cog-aibox-la5
  (x) Failed: Private Endpoint: pl-cog-aibox-la5
  | ======| Creating/Updating resources
ERROR: error executing step command 'provision': deployment failed: error deploying infrastructure: deploying to subscription:

Deployment Error Details:
AccountProvisioningStateInvalid: Call to Microsoft.CognitiveServices/accounts failed. Error message: Account /subscriptions/04xxxxxxxxxxxxxxxxxxxxxxxxxxxxx96b/resourceGroups/rg-aibox/providers/Microsoft.CognitiveServices/accounts/cog-aibox-la5 in state Accepted
AccountProvisioningStateInvalid: Call to Microsoft.CognitiveServices/accounts failed. Error message: Account /subscriptions/04xxxxxxxxxxxxxxxxxxxxxxxxxxxxx96b/resourceGroups/rg-aibox/providers/Microsoft.CognitiveServices/accounts/cog-aibox-la5 in state Accepted
RoleAssignmentExists: The role assignment already exists.
PrincipalNotFound: Principal 7517xxxxxxxxxxx7e83 does not exist in the directory f7aabb16-79a8-4ca2-887e-2ad0630f30f4. Check that you have the correct principal ID. If you are creating this principal and then immediately assigning a role, this error might be related to a replication delay. In this case, set the role assignment principalType property to a value, such as ServicePrincipal, User, or Group.  See https://aka.ms/docs-principaltype

TraceID: 523256143d053f3b89138fce9fc510ed
PS C:\ai-studio-in-a-box> azd up

Packaging services (azd package)


Provisioning Azure resources (azd provision)
Provisioning Azure resources can take some time.

Subscription: Microsoft Azure Sponsorship Subscription 3 (04xxxxxxxxxxxxxxxxxxxxxxxxxxxxx96b)
Location: East US 2

  You can view detailed progress in the Azure Portal:
  https://portal.azure.com/#view/HubsExtension/DeploymentDetailsBlade/~/overview/id/%2Fsubscriptions%2F04xxxxxxxxxxxxxxxxxxxxxxxxxxxxx96b%2Fproviders%2FMicrosoft.Resources%2Fdeployments%2Faibox-1722355454

  (✓) Done: Resource group: rg-dns
  |===    | Creating/Updating resources
ERROR: error executing step command 'provision': deployment failed: error deploying infrastructure: deploying to subscription:

Deployment Error Details:
PrincipalNotFound: Principal 7517xxxxxxxxxxx7e83 does not exist in the directory f7aabb16-79a8-4ca2-887e-2ad0630f30f4. Check that you have the correct principal ID. If you are creating this principal and then immediately assigning a role, this error might be related to a replication delay. In this case, set the role assignment principalType property to a value, such as ServicePrincipal, User, or Group.
RoleAssignmentExists: The role assignment already exists.`

**Comment by MarcoABCardoso** [comment]
Hello @IainD925,

It seems your Principal ID does not match your directory - you may be logged in as different users in `az` and `azd`.
Re-authenticating with both may solve your issue.

**Comment by MarcoABCardoso** [comment]
@lenisha The Compute Instance creation issue is solved from the Azure AI Side - you should no longer run into issues when setting up identity-based access.

Closing this issue as it was the one reported initially - please feel free to open new issues on other items!
