### ISSUE TITLE
Service Principal not created

### ISSUE THREAD

**Issue by IainD925** [Azure-Samples/ai-studio-in-a-box#4]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> See below (steps, logs and confirmation az and azd attached to same subscription)

### Any log messages given by the failure

`Disconnect-AzAccount

Id                    : Me@my.co.uk
Type                  : User
Tenants               : {f7aabb16-123-456-abcd30f4}
Credential            :
TenantMap             : {}
CertificateThumbprint :
ExtendedProperties    : {[Tenants, f7aabb16-123-456-abcd30f4], [HomeAccountId,
                        50ea9975-abcd-1234-de49da77ca4d.f7aabb16-123-456-abcd30f4]}

PS C:\Users\Me> $sub = '041a5d-1234-5678-abcd-d3e1ad96b'
PS C:\Users\Me> cd c:\
PS C:\> git clone https://github.com/Azure-Samples/ai-studio-in-a-box
Cloning into 'ai-studio-in-a-box'...
remote: Enumerating objects: 168, done.
remote: Counting objects: 100% (168/168), done.
remote: Compressing objects: 100% (128/128), done.
remote: Total 168 (delta 32), reused 162 (delta 26), pack-reused 0
Receiving objects: 100% (168/168), 15.54 MiB | 31.38 MiB/s, done.
Resolving deltas: 100% (32/32), done.
PS C:\> cd ai-studio-in-a-box
PS C:\ai-studio-in-a-box> azd env new
? Enter a new environment name: [? for help] aiinabox

? Enter a new environment name: aiinabox
PS C:\ai-studio-in-a-box>
PS C:\ai-studio-in-a-box> Connect-AzAccount -SubscriptionId $sub

Account                    SubscriptionName                           TenantId                             Environment
-------                    ----------------                           --------                             -----------
Me@my.co.uk Microsoft Azure Sponsorship Subscription 3 f7aabb16-123-456-abcd30f4 AzureCloud

PS C:\ai-studio-in-a-box>
PS C:\ai-studio-in-a-box> # Check Az is connected to the correct sub
PS C:\ai-studio-in-a-box> $context = Get-AzContext
PS C:\ai-studio-in-a-box>
PS C:\ai-studio-in-a-box> if ($null -eq $context) {
     Write-Output "You are not logged into Azure."
 } else {
     Write-Output "Az is logged into Azure."
     Write-Output "Account: $($context.Account)"
     Write-Output "Az Subscription NAME: $($context.Subscription.Name)"
 }
Az is logged into Azure.
Account: Me@my.co.uk
Az Subscription NAME: Microsoft Azure Sponsorship Subscription 3
PS C:\ai-studio-in-a-box>
PS C:\ai-studio-in-a-box> # Deploying to Azure
PS C:\ai-studio-in-a-box> azd up
? Select an Azure Subscription to use:  3. Microsoft Azure Sponsorship Subscription 3 (04**1a5d-1234-5678-abcd-***d3e1ad96b)
? Select an Azure location to use: 45. (US) East US 2 (eastus2)
? Enter a value for the 'deploySearch' infrastructure parameter: True
? Enter a value for the 'publicNetworkAccess' infrastructure parameter: Enabled
? Enter a value for the 'systemDatastoresAuthMode' infrastructure parameter: identity

Packaging services (azd package)

Provisioning Azure resources (azd provision)
Provisioning Azure resources can take some time.

Subscription: Microsoft Azure Sponsorship Subscription 3 (04**1a5d-1234-5678-abcd-***d3e1ad96b)
Location: East US 2

  You can view detailed progress in the Azure Portal:
  https://portal.azure.com/#view/HubsExtension/DeploymentDetailsBlade/~/overview/id/%2Fsubscriptions%2F04**1a5d-1234-5678-abcd-***d3e1ad96b%2Fproviders%2FMicrosoft.Resources%2Fdeployments%2Faiinabox-1722433557

  (✓) Done: Resource group: rg-aiinabox
  (✓) Done: Virtual Network: vnet-aiinabox-whq
  |==     | Creating/Updating resources                                                                           (✓) Done: Key Vault: kv-aiinabox-whq
  (✓) Done: Storage account: staiinaboxwhq
  (✓) Done: Private Endpoint: pl-staiinaboxwhq
  (✓) Done: Private Endpoint: pl-kv-aiinabox-whq
  (✓) Done: Search service: srch-aiinabox-whq
  (✓) Done: Private Endpoint: pl-srch-aiinabox-whq
  (✓) Done: Cognitive Service: cog-aiinabox-whq
  (x) Failed: Private Endpoint: pl-cog-aiinabox-whq
  (x) Failed: Private Endpoint: pl-oai-cog-aiinabox-whq
  |  =====| Creating/Updating resources
ERROR: error executing step command 'provision': deployment failed: error deploying infrastructure: deploying to subscription:

Deployment Error Details:
AccountProvisioningStateInvalid: Call to Microsoft.CognitiveServices/accounts failed. Error message: Account /subscriptions/041a5d-1234-5678-abcd-d3e1ad96b/resourceGroups/rg-aiinabox/providers/Microsoft.CognitiveServices/accounts/cog-aiinabox-whq in state Accepted
AccountProvisioningStateInvalid: Call to Microsoft.CognitiveServices/accounts failed. Error message: Account /subscriptions/041a5d-1234-5678-abcd-d3e1ad96b/resourceGroups/rg-aiinabox/providers/Microsoft.CognitiveServices/accounts/cog-aiinabox-whq in state Accepted
PrincipalNotFound: Principal 75174c44eec74a6bb2e3a3d780497e83 does not exist in the directory f7aabb16-123-456-abcd30f4. Check that you have the correct principal ID. If you are creating this principal and then immediately assigning a role, this error might be related to a replication delay. In this case, set the role assignment principalType property to a value, such as ServicePrincipal, User, or Group.  See https://aka.ms/docs-principaltype

TraceID: 7307df90bf829bffb805da261520f53a
PS C:\ai-studio-in-a-box>
PS C:\ai-studio-in-a-box> # Checking Azd is connected to the correct sub
PS C:\ai-studio-in-a-box> $azdSub = azd env get-values
PS C:\ai-studio-in-a-box>
PS C:\ai-studio-in-a-box> # Extract the line containing the subscription ID
PS C:\ai-studio-in-a-box> $subscriptionLine = $azdSub | Where-Object { $_ -match "AZURE_SUBSCRIPTION_ID" }
PS C:\ai-studio-in-a-box>
PS C:\ai-studio-in-a-box> # Extract the actual subscription ID value
PS C:\ai-studio-in-a-box> $subscriptionId = $subscriptionLine -replace '.*="([^"]*)".*', '$1'
PS C:\ai-studio-in-a-box>
PS C:\ai-studio-in-a-box> if ($context.Subscription.Id -eq $subscriptionId) {
 Write-Output "Az  SubscriptionId: $($context.Subscription.Id)"
 Write-Output "Azd SubscriptionId: $subscriptionId"
     Write-Output "Az and Azd Subscriptions Match"
 } else {
     Write-Output "Az and Azd Subscriptions Do NOT Match!"
 }
 
Az   SubscriptionId: 041a5d-1234-5678-abcd-d3e1ad96b
Azd SubscriptionId: 041a5d-1234-5678-abcd-d3e1ad96b

Az and Azd Subscriptions Match`

### Expected/desired behavior
> Owner role and 'Application Administrator' roles sufficient to create service principal and assign permissions.

### OS and Version?
> Windows 10

### Versions
> [372965f](https://github.com/Azure-Samples/ai-studio-in-a-box/commit/372965f52389843a4ea9d297790ef85ebecb6ccb)

### Mention any other details that might be useful
> Please advise if the service principal is hardcoded (always appears to be 75174c44eec74a6bb2e3a3d780497e83) - even if I try to set the environment variable to a App Registration object ID like so: 
> azd env set PRINCIPAL_ID 2c98fc67-1234-abcd-bed0-ee8a5559d914
The error remains : 
PrincipalNotFound: Principal 75174c44eec74a6bb2e3a3d780497e83 does not exist in the directory f7aabb16-123-456-abcd30f4

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by MarcoABCardoso** [comment]
Hello @IainD925! 
Thank you for taking the time to provide additional details on your issue.

To elaborate on the setup details - there is a `preup` hook in azure.yaml which is expected to set PRINCIPAL_ID to your own currently logged in user. The code it runs is:
```
azd env set PRINCIPAL_ID $(az ad signed-in-user show --query id -o tsv)
```
This explains why setting it manually doesn't alter the results. you may run `azd provision` rather than `azd up` to skip this hook.

The purpose of this is to grant access to the current identity (usually the user) on all services, so they can immediately explore the platform. Your issue is specifically that the user returned from `az ad signed-in-user show` is not on the tenant you are deploying to.

Can you confirm that the AZURE_TENANT_ID returned by `azd env get-values` is the one the subscription is in?

**Comment by IainD925** [comment]
> Can you confirm that the AZURE_TENANT_ID returned by `azd env get-values` is the one the subscription is in?

Thanks @MarcoABCardoso - I can confirm that the Tenant ID contains the Subscription (3) that I am using.
'Azd up' creates the majority of resources in this subscription, across the two resource groups.

**Comment by MarcoABCardoso** [comment]
Thank you for confirming.

I'll run a few tests with different user types to see if I can reproduce your issue, and update shortly.

**Comment by IainD925** [comment]
> To elaborate on the setup details - there is a preup hook in azure.yaml which is expected to set PRINCIPAL_ID to your own currently logged in user. The code it runs is: azd env set PRINCIPAL_ID $(az ad signed-in-user show --query id -o tsv)

Ah!  Now this is interesting - running `az ad signed-in-user show` shows that account is for a different tenant.  I don't know how it's doing it given I'm starting a new session each time at starting with Disconnect-AzAccount

Will pick up again tmr: thank-you!

**Comment by MarcoABCardoso** [comment]
Yes! I managed to reproduce your exact error message by running `az login -t <wrong tenant ID>`.
Please let me know if you continue to see the issue after confirming `az ad signed-in-user show` gives you the right tenant.

**Comment by IainD925** [comment]
Resolved!  Really interesting -  I thought `Connect-AzAccount` authenticating with my subscription was all I needed but I learned that only connects PowerShell.  The Azure CLI needs `az login`.
Thanks for you help @MarcoABCardoso
