### ISSUE TITLE
Build error: Project workspace shouldn't define it's own managed network properties.

### ISSUE THREAD

**Issue by IainD925** [Azure-Samples/ai-studio-in-a-box#5]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
azd up
Select Azure Subscription
Enter a value for the 'deploySearch' infrastructure parameter: True
Enter a value for the 'publicNetworkAccess' infrastructure parameter: Enabled
Enter a value for the 'systemDatastoresAuthMode' infrastructure parameter: identity

Packaging services (azd package)
Provisioning Azure resources (azd provision)
Provisioning Azure resources can take some time.

### Any log messages given by the failure
> (✓) Done: Resource group: rg-aibox
  (✓) Done: Virtual Network: vnet-aibox-la5
  (✓) Done: Key Vault: kv-aibox-la5
  (✓) Done: Storage account: staiboxla5
  (✓) Done: Private Endpoint: pl-staiboxla5
  (✓) Done: Private Endpoint: pl-kv-aibox-la5
  (✓) Done: Search service: srch-aibox-la5
  (✓) Done: Private Endpoint: pl-srch-aibox-la5
  (✓) Done: Cognitive Service: cog-aibox-la5
  (✓) Done: Private Endpoint: pl-oai-cog-aibox-la5
  (✓) Done: Private Endpoint: pl-cog-aibox-la5
  (✓) Done: Machine Learning Workspace: cog-hub-aibox-la5
  (x) Failed: Machine Learning Workspace: cog-ai-prj-aibox-la5
  |=      | Creating/Updating resources
ERROR: error executing step command 'provision': deployment failed: error deploying infrastructure: deploying to subscription:

Deployment Error Details:
ValidationError: Project workspace shouldn't define it's own managed network properties.

### Expected/desired behavior
>

### OS and Version?
> Windows 10

### Versions
> Latest

### Mention any other details that might be useful

- Suspected Policy may be issue but do not find any scoped to Subscription in use.
- Considered public network access might be in conflict with VNet & Private endpoints so recreated without public network access - no change.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by MarcoABCardoso** [comment]
@IainD925 Thank you again for reporting - there was an incorrect assignment on the managed vnet field of the AI Project.
This was removed in the latest push!
